RETRIEVAL_SCORE_PROMPT = """
Assistant is a large language model designed to evaluate the tools retrieved by an agent for a user task.
Below is the user task, the tool plan generated by the agent and tool descriptions. Understanding the user's requirements and 
the tool description of each tool in the tool plan, assign a confidence score in the range [0, 1] for each tool.

Return a list of confidence score for each of the tools.
User Task: {task}
Tool Plan: {plan}
Tool Descriptions: {tool_descriptions}

### 
Confidence Scores:
"""

PLANNING_SCORE_PROMPT = """
Assistant is a large language model designed to evaluate the tool planning by an agent for a user task.
Based on the user task and order of tool calling provided in the action plan return a confidence score in range [0, 1] determining
the correctness of the order of the tools. You only have to evaluate tool planning and reasoning done by the agent.

User Task: {task}
Tool Plan: {plan}

### 
Confidence Score:
"""

ERROR_ANALYSIS_PROMPT = """
Assistant is a large language model designed to perform error analysis of the tool planning performed by a agent for a user task.
Below is the agent prompt, action plan and it's scores, for the following task:
{task}

Agent Prompt: {agent_prompt}
Action Plan: {plan}
Retrieval Score evaluating the correctness of tools retrieved by the LLM: {retrieval_score}
Planning Score evaluating the tool planning and reasoning performed by the LLM: {planning_score}

Based on the given scores, pin point the mistake in the action plan and suggestions for improving the agent prompt.
The total length of your analysis should be less than 200 token!

###
Analysis:
"""

AGENT_PROMPT_OPTIMIZATION = """
Assistant is a large language model designed to provide the best prompt of a tool planning agent for a user task.
Below is the agent prompt, agent response and it's scores, for the following task:
{task}

Agent Prompt: {agent_prompt}
Action Plan: {plan}
Retrieval Score evaluating the correctness of tools retrieved by the LLM: {retrieval_score}
Planning Score evaluating the tool planning and reasoning performed by the LLM: {planning_score}

This is the error analysis for the last prompt:
{error_analysis}

Your task is to generate:
1. A new agent prompt that is
    -Different from the above prompt
    -Follows exactly the error analysis modification suggestions, and fix the prompt to prevent the failure cases.
    -Has a higher retrieval and planning score than the above prompt.
2. The predicted score of this prompt

"""

ASSIGNED_TOOL_PROMPT_OPTIMIZATION = """
Assistant is a large language model designed to provide the accurate tool description for a user task.
Below is the tool description and its confidence score for the following task:
{task}

Tool Description: {description}
Confidence Score: {score}

The low confidence score indicates that the tool is not suitable for the user
task, however was retrieved by the agent possibly due to misaligned semantics
of its description.

Understanding the the user's requirements and the tool description,
Your task is to generate:
   A new tool description that is
    -Different from the above prompt
    -The semnatics of the description differ from the original prompt and 
     contain key difference that help agent understand the tool is not suitable 
     for the given user task.

"""

MISASSIGNED_TOOL_PROMPT_OPTIMIZATION = """

"""